### ISSUE TITLE
regex filter

### ISSUE THREAD

**Issue by kordaleas** [carrotquest/django-clickhouse#14]
Hello, 

I would like to use the package for my django & clickhouse project, but I found out there is no support for __regex operator for filtering. Any suggestions from your side to overcome this problem?

Thanks in advance,
Alex

**Comment by M1ha-Shvn** [comment]
Hi.
This library QuerySet and filter system is fully built over [infi.clickhouse-orm QuerySet system](https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/querysets.md#querysets). As a result, it's more an issue for infi, than for this library.
The latest value of infi.clickhouse-orm (prior to 2.0.0) gives many built in [`F.*` functions](https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/expressions.md) you can use. May be you can find answer there. If not, I recommend to submit this issue to them.
