### ISSUE TITLE
Different clickhouse db url

### ISSUE THREAD

**Issue by dimamotsik** [carrotquest/django-clickhouse#17]
How can I add different clickhouse url into settings?

**Comment by M1ha-Shvn** [comment]
Hi.
You can set url using `db_url` key in `CLICKHOUSE_DATABASES` setting.  Here are [the docs](https://github.com/carrotquest/django-clickhouse/blob/master/docs/configuration.md#clickhouse_databases). This setting keys are derived from [infi.clickhouse-orm Database settings](https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/class_reference.md#database)

**Comment by dimamotsik** [comment]
Thanks!
