### ISSUE TITLE
Error when migrating

### ISSUE THREAD

**Issue by icychocolate98** [carrotquest/django-clickhouse#18]
Good morning,

First of all thank you by this great library you deployed.
I'm doing some tests trying to implement Django with Clickhouse, It's almost done but I get the following error:

`django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.`

I know is something realted with database instances but I canot find the detail.
It's like its trying to use my "DATABASES" object but I want Django to use "CLICKHOUSE_DATABASES" how could I perform that?

I have following lines in my "settings.py" file:
```
CLICKHOUSE_DATABASES = {
    'clickhouse-db': {
        'db_url' : 'http://localhost:8123/',
        'db_name': 'db_name',
        'username': 'username',
        'password': 'xxxxx.'
    }
}

from django_clickhouse.database import connections
db = connections['clickhouse-django']
db_link = connections['clickhouse-django'] 
```

Thank you a lot in advice!

**Comment by M1ha-Shvn** [comment]
Hi
`CLICKHOUSE_DATABASES` and django's `DATABASES` settings are not anyhow connected. Your exceptions tell that you haven't defined `DATABASES` and django requires this setting. You can use simple "empty" configuration if you don't need any databases other than Clickhouse:
```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'mydatabase',
    }
}
```
Here are [the docs](https://docs.djangoproject.com/en/3.1/ref/settings/#databases)

P. s. I'm not sure, what you are trying to do here, but you should use `clickhouse-db` instead of `clickhouse-django` as connection name, as it is used in `CLICKHOUSE_DATABASES`:
```python
from django_clickhouse.database import connections
db = connections['clickhouse-db']
db_link = connections['clickhouse-db'] 
```

**Comment by icychocolate98** [comment]
Yeah I'm using the same name, I have tried to recreate a simple "example".

So I need to define Databases 100% with a default value as that of sqlite3? Oh...

Other quick question : 
How I made requests to any table?

Thank you!

**Comment by M1ha-Shvn** [comment]
Here are [the docs](https://github.com/carrotquest/django-clickhouse/blob/master/docs/queries.md)

**Comment by icychocolate98** [comment]
Thank you a lot!

I'm almost done, I'm having some problems selecting data from db, using db.select I get this error:

```
myenv/lib/python3.8/site-packages/infi/clickhouse_orm/models.py", line 395, in from_tsv
    kwargs[name] = field.to_python(next(values), field_timezone)

Exception Type: AttributeError at /app1/route1
Exception Value: 'tuple' object has no attribute 'to_python'
```

My query is something like this:
```
 for customer in db.select("SELECT field1,field2 FROM my_database.model_name", model_class=model_name):
        print(model_name.field1, model_name.field2)
```

Do you have any idea on what can raise this error? Thank you in advice!

Moreover, using querySet I can access data but I cannot see its value properly ... 
If I use querySet I reach almost a correct result but when I do a print on this  loop:
```
db = Database( ... ) # Init db.

qs_result = customers.objects_in(db)

for customer in qs_result:
    print(customer.id)
```
I only see something like this, it's a string but I want to see the field value... 
`(<StringField>,)`

**Comment by M1ha-Shvn** [comment]
> `for customer in db.select("SELECT field1,field2 FROM my_database.model_name", model_class=model_name):`
> `       print(model_name.field1, model_name.field2)`

Your query returns `customer` objects. not `model_name`. You can access it via `customer.field1, customer.field2`.

If you use this library with django, you should not use `Database` objects directly (you can do so, but it will break connection caching). If you've defined `CLICKHOUSE_DATABASES` you can use [aliases like in django](https://github.com/carrotquest/django-clickhouse/blob/master/docs/queries.md#django-like-routing-system). They will be routed automatically like django does and create appropreiate connections under the hood:
```python
class Customer(Model):
    field1 = StringField()
    field2 = StringField()
    
qs1 = customers.objects.all()  # will use 'default' database alias from CLICKHOUSE_DATGABASES
qs2 = customers.objects.using('other_db').all()  # will use 'other_db' database alias from CLICKHOUSE_DATGABASES

for customer in qs1:
    print(customer.field1)
```

> I only see something like this, it's a string but I want to see the field value...
> `(<StringField>,)`

I don't know how your model is defined. So I can not say why it returns a tuple in id field.

**Comment by icychocolate98** [comment]
Good afternoon!

It was a problem with what you mentioned "If you use this library with django, you should not use Database objects directly (you can do so, but it will break connection caching)." Now it's solved, I need to use objects.using().all()!

Moreover I can catch my fields, but It's still the same problem, it's impossible to print any field value, e.g:
```
query_set = model.objects.using('my_db').all()
    for item in query_set.all():
        print(item.id)
```

I'm doing that but I got something like this:
```
(<StringField>,)
(<StringField>,)
(<StringField>,)
(<StringField>,)
(<StringField>,)
(<StringField>,)
```

It's like it's coming a tuple on that field!

`id = fields.StringField(),`

And in my models.py (django models) something like this:

`id = models.CharField(max_length=50, primary_key=True),`

Do you have any idea on what it's happening?
Thank you a lot!

**Comment by M1ha-Shvn** [comment]
Is there a comma at the end of line in your code? Of course, adding a comma makes python interpret attribute value as a tuple and you get (StringField(),). At the same time, I suppose library does not see these fields, as it looks for Field instances not tuples.
