### ISSUE TITLE
A release on PyPi

### ISSUE THREAD

**Issue by pikhovkin** [carrotquest/django-clickhouse#3]

**Comment by M1ha-Shvn** [comment]
Hi, I'm planning pypi release after the readme is written, but I'm not sure, when I have time for it.

**Comment by utapyngo** [comment]
Any news about the planned release date?

**Comment by Mogost** [comment]
Ping @M1hacka

**Comment by M1ha-Shvn** [comment]
Hi. 
Sorry for long delay. 
I'll try to finish the docs this month and make a release.

**Comment by M1ha-Shvn** [comment]
Released [Version 1.0.0](https://github.com/carrotquest/django-clickhouse/releases/tag/v1.0.0)
