### ISSUE TITLE
migrate_app doesn't look for the current applied migrations in the specified database

### ISSUE THREAD

**Issue by Reve** [carrotquest/django-clickhouse#30]
Using debug I found out that migrate_app is using a migration_history_model from the 'default' database even though I specified a 'testing' database, resulting that the migrations are never applied to the 'testing' database.

Also please allow to specify a testing database in order not to alter the 'default' database. Thank you for your work :)

**Comment by Reve** [comment]
This is a workaround I found that is working for now.

```
@pytest.fixture(scope="session")
def test_db_setup():
    from django.conf import settings

    settings.CLICKHOUSE_DATABASES["default"]["db_name"] = "test_db"

    yield


@pytest.fixture(scope="session", autouse=True)
def click_db(test_db_setup):
    db = connections["default"]
    db.drop_database()
    db.db_exists = False
    db.create_database()

    migrate_app("reports", "default")
    return db
```

**Comment by M1ha-Shvn** [comment]
Hi, Reve
Yes, by default design migration table is stored in default database. It stores information about migrations, applied to any database from `CLICKHOUSE_DATABASES` setting. I've chosen this design, as far as ClickHouse is a multi-master database, it supports per table replication and some of `CLICKHOUSE_DATABASES` can be readonly replica of single table, for instance. Or something like [chproxy](https://github.com/Vertamedia/chproxy), splitting requests to multiple database instances.  Or some other unexpected topology.
If you want to modify this behavior, you can inherit your own migration history model as you wish (in my own case, I make it replicated, for instance) and set it via `MIGRATION_HISTORY_MODEL` setting. You can easily change databases using `read_db_aliases`, `write_db_aliases`, `migrate_replicated_db_aliases`, `migrate_non_replicated_db_aliases` attributes. More than that, you can do anything you want, redeclaring model methods.
[Here are the docs about setting you custom migration model](https://github.com/carrotquest/django-clickhouse/blob/master/docs/migrations.md#migrationhistory-clickhousemodel)
[Here is the default MigrationHistory model](https://github.com/carrotquest/django-clickhouse/blob/master/src/django_clickhouse/migrations.py#L103)

**Comment by M1ha-Shvn** [comment]
Closing for no reaction

**Comment by Reve** [comment]
Thank you for the suggestions and sorry for the late reply
