### ISSUE TITLE
Clickhouse migrations are ignored when the app doesn't have regular migrations

### ISSUE THREAD

**Issue by Reve** [carrotquest/django-clickhouse#31]
If you have an app that has clickhouse_migrations but no regular migrations, the migrate command will not check the app and the clickhouse_migrations are ignored. One workaround I found was to include an apps.py file in your app folder and run the migrations manually.

apps.py:
```
from django.apps import AppConfig

class Config(AppConfig):
    name = "reports"

    def ready(self):
        from django_clickhouse.migrations import migrate_app

        migrate_app("reports", "default")
```

**Comment by M1ha-Shvn** [comment]
Hi, Reve.
Default migration system catches [django's `post_migrate` signal](https://docs.djangoproject.com/en/3.2/ref/signals/#post-migrate). I guess that in your case it is not emmited. I see such a phrase in the docs:
`It’s not emitted for applications that lack a models module.`
May be it is not also emmited, if there are no `migrations` module in the app. If this is correct, there is nothing I can do here - only implement some system separated from `manage.py migrate` for making clickhouse migrations.

You proposal about `AppConfig` will work, but I suppose it will call migrations every time you load django code (may be, in each thread/process, if you use something multithreaded like celery/gunicorn). I think it won't break anything, though I don't think it is a good approach.

I have an idea of making [custom command](https://docs.djangoproject.com/en/3.2/howto/custom-management-commands/) `manage.py clickhouse_migrate`, but I'm not sure when I'll get to this task. If you can implement it - I will be greatful for a PR. Please, reply if this migration design can suit your needs.

**Comment by Reve** [comment]
You are right, calling migrate_app in AppConfig adds a lot of overhead. I will try making a custom clickhouse_migrate command and add a pull request when it is done.

**Comment by simion** [comment]
Having the same issue.

fixed with custom command + setting `CLICKHOUSE_MIGRATE_WITH_DEFAULT_DB = False`

```python
from django.apps import apps
from django.core.management import BaseCommand
from django_clickhouse.migrations import migrate_app
from django_clickhouse.configuration import config as config


class Command(BaseCommand):
    def handle(self, *args, **options):
        for app_config in apps.get_app_configs():
            for db_alias in config.DATABASES:
                migrate_app(app_config.module.__name__, db_alias)
```
(I haven't checked if clickhouse_migrations package exists, because they are already checking it in `migrate_app`)

**Comment by M1ha-Shvn** [comment]
Hi guys, in [this PR](https://github.com/carrotquest/django-clickhouse/pull/33) I've implemented a full featured django `clickhouse_migrate` command for `manage.py`. As soon as tests pass, I'll make a release. You can read more about command [here](https://github.com/carrotquest/django-clickhouse/blob/migrate-command/issue-31/docs/migrations.md#admin-migration-command)

**Comment by M1ha-Shvn** [comment]
Released [v1.1.0](https://github.com/carrotquest/django-clickhouse/releases/tag/v1.1.0)

**Comment by simion** [comment]
> Hi guys, in [this PR](https://github.com/carrotquest/django-clickhouse/pull/33) I've implemented a full featured django `clickhouse_migrate` command for `manage.py`. As soon as tests pass, I'll make a release. You can read more about command [here](https://github.com/carrotquest/django-clickhouse/blob/migrate-command/issue-31/docs/migrations.md#admin-migration-command)

@M1ha-Shvn  It crashes when you install an app by it's config.

```
    spam_spec = find_spec(module_name)
  File "/Users/simion/.pyenv/versions/3.8.5/lib/python3.8/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'dashboards.apps.DashboardsConfig'; 'dashboards.apps' is not a package
```

that's how i added the app:

```python
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #...
    'dashboards.apps.DashboardsConfig',  # here
    'widgets.apps.WidgetsConfig',
]
```

However, if i specify just one app for migration, it works:
```
./manage.py clickhouse_migrate dashboard
```

**Comment by M1ha-Shvn** [comment]
Hi, @simion .
I've opened a separate issue for that
