### ISSUE TITLE
RunSQL and RunPython are not supported for migrations

### ISSUE THREAD

**Issue by amrhgh** [carrotquest/django-clickhouse#40]
Hi

as I realize, before any migration router check to find out list of allowed databases for specific operation.
for model operation, allowed databases are specified in the model itself, but in nonmodel operations model is not defined.
migration try to access hints dictionary from operation to find allowed databases from **force_migrate_on_databases** or **model** fields, but not supported in clickhouse_orm.
how can I migrate nonmodel operations properly ? 
is there any way to support these operations ?

**Comment by M1ha-Shvn** [comment]
Hi.
As mentioned [here](https://github.com/carrotquest/django-clickhouse/blob/master/docs/migrations.md#migrations), django-clickhouse inherits its migration from [infi.clickhouse-orm](https://github.com/Infinidat/infi.clickhouse_orm). And it has [RunPython](https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/schema_migrations.md#runpython) and [RunSQL](https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/schema_migrations.md#runsql) migrations. Do they suit your needs?

**Comment by amrhgh** [comment]
yes, these operations are supported by clickhouse-orm.
the problem is that before applying migration to each databases router check migration should be applied to the database or not with **allow_migrate** method:

https://github.com/carrotquest/django-clickhouse/blob/01cec7c999002976ea7b43a0833d8a1add42cf41/src/django_clickhouse/migrations.py


for model operations like CreateTable allowed databases are defined inside the model but for nonmodel operation allowed databases should specify in the operation hints attribute which is not supported in clickhouse-orm.

for example, this is the init function of RunSQL.its just except SQL :

https://github.com/Infinidat/infi.clickhouse_orm/blob/232a8d29ad237c833d3c851e1d61989ff55d7bd8/src/infi/clickhouse_orm/migrations.py#L245

my question is whether there is any way to support these operations or at least I think it is better to add a solution in the doc

**Comment by M1ha-Shvn** [comment]
Hints don't look hard to implement. We can inherit `infi.clickhouse_orm` operations in `django_clickhouse.migrations`, adding extra parameters and processing them in our basic router. 
Though I can't say when I'll do it. If you can help, we are always ready to accept PRs.

**Comment by amrhgh** [comment]
yes, I can do it.

**Comment by amrhgh** [comment]
https://github.com/carrotquest/django-clickhouse/pull/41

**Comment by M1ha-Shvn** [comment]
Released [v1.2.0](https://github.com/carrotquest/django-clickhouse/releases/tag/v1.2.0)
