### ISSUE TITLE
how to use array join for ORM

### ISSUE THREAD

**Issue by hejianxin159** [carrotquest/django-clickhouse#43]
example： 
     select toys toy, count() from User array join toys group by toys

**Comment by M1ha-Shvn** [comment]
Hi, @hejianxin159.
This library does not implement QuerySet functionality. It relies on features, realized in [infi.clickhouse_orm](https://github.com/Infinidat/infi.clickhouse_orm).
Unfortunately functionality for joining tables is not implemented there, as I remember. There is [my old issue](https://github.com/Infinidat/infi.clickhouse_orm/issues/147), requesting this functionality, but it is still opened. More than that it looks like infi libaray is [nearly stale nowadays](https://github.com/Infinidat/infi.clickhouse_orm/issues/176). I'll transfer this issue there, but I can not tell you how long it will take to implement your request...

**Comment by hejianxin159** [comment]
> Hi, @hejianxin159. This library does not implement QuerySet functionality. It relies on features, realized in [infi.clickhouse_orm](https://github.com/Infinidat/infi.clickhouse_orm). Unfortunately functionality for joining tables is not implemented there, as I remember. There is [my old issue](https://github.com/Infinidat/infi.clickhouse_orm/issues/147), requesting this functionality, but it is still opened. More than that it looks like infi libaray is [nearly stale nowadays](https://github.com/Infinidat/infi.clickhouse_orm/issues/176). I'll transfer this issue there, but I can not tell you how long it will take to implement your request...

oh, thank you
