### ISSUE TITLE
`ClickHouseModel` subclass initialization problem

### ISSUE THREAD

**Issue by v-spassky** [carrotquest/django-clickhouse#51]
Hello!

When using the library a came across an issue: in short, I couldn't get the synchronization working.

I had a ClickHouse model like this:

```python
# myapp/clickhouse_models.py

class MyCHModel(ClickHouseModel):
    django_model = MyDjangoModel
    sync_enabled = True
    sync_batch_size = ...
    engine = ReplacingMergeTree(...)

    id = Int64Field()
    ...
```

The periodic task was scheduled as it should be and Celery was running it, but the logs were saying smth like `django-clickhouse: removed 0 operations from storage (key: MyCHModel)` despite actually applying a ton of modifications to the related Django model and saving model instances.

When inspecting this I found that the code in `ClickHouseModelMeta.__new__()` was not running for `MyCHModel` when running `python3 manage.py runserver`, for example. To make it run I decided to do the same trick which is typically done for registering signal handlers:

```python
# myapp/apps.py

from django.apps import AppConfig


class MyAppConfig(AppConfig):
    name = 'myapp'

    def ready(self):
        from myapp.clickhouse_models import MyCHModel
```

This way I'm triggering `ClickHouseModelMeta.__new__()` for `MyCHModel` and it gets registered for synchronization successfully and the `MyCHModel` actually gets synced with `MyDjangoModel`.

But I'm wondering if this is intended and known about or it isn't and I just made a mistake somewhere along the way and synchronization should work without this? If it's the former - maybe it is worth mentioning in the docs?

And btw, thanks for the well done library!

---

Versions:

- Python `3.10.12`
- Django `4.1.3` 
- django-clickhouse `1.2.1`

**Comment by M1ha-Shvn** [comment]
Hi @v-spassky.
As I understood, the real problem in you case is that `MyCHModel` is never imported anywhere in the code - so the class is not anywhere created by python interpreter and, as a result,, `ClickHouseModelMeta` metaclass is not called. 

Your fix helped, as it began importing your model during django initialization. The same effect you would receive if you simply import your package somewhere in your code like:
```python
from my_app.clickhouse_models import MyDJangoModel
```
Correct me, please, if I'm not right.

I'm not really sure what can be done with it in library code, as it is not library model, that is not imported anywhere. I guess, you are right and it would be worth mentioning somewhere in the docs. Where do you expect it to be?

**Comment by v-spassky** [comment]
In my case, `MyCHModel` actually gets imported only in one place in the whole project like this:

```python
# in myapp2/views.py

from myapp.clickhouse_models import MyCHModel

...

class MyCHView(APIView):
    def get(self, request, *_args, **_kwargs):
        res = MyCHModel.get_whatever_info(request.user.id)
        return Response(res)

...
```

, and this related view is then imported like this:

```python
# in myapp2/urls.py

from django.urls import path

from myapp2.views import MyCHView


urlpatterns = [
    path('whatever-info/', MyCHView.as_view()),
]
```

Ofc, `myapp2` is included in `INSTALLED_APPS` and the root `urls.py` module includes `myapp2.urls` into its `urlpatterns` list. Not sure why Django's initialization process isn't reaching `MyCHModel` with such setup...

> I'm not really sure what can be done with it in library code, as it is not library model, that is not imported anywhere.

That's ok. Personally, I don't see any problem doing the `def ready(self)` trick. Everybody is used to doing that with signals anyway.

> Where do you expect it to be?

Imo, that would make sense to mention it in the [overview](https://github.com/carrotquest/django-clickhouse/blob/master/docs/overview.md) page which effectively works as a quick start guide, maybe right after [this](https://github.com/carrotquest/django-clickhouse/blob/master/docs/overview.md#create-clickhousemodel) section.

**Comment by M1ha-Shvn** [comment]
Added a note to docs
