### ISSUE TITLE
Window func django-clickhouse

### ISSUE THREAD

**Issue by PavelIgin** [carrotquest/django-clickhouse#52]
How i can use Window func in your orm?? Now i user raw() but its hard)))

exclude_next = Q(value=F('next_value')) | Q(value=F('second_next_value'))
exclude_prev = Q(value=F('prev_value')) | Q(value=F('second_prev_value'))
queryset = ValueChart.objects.filter(signal_id=signal.id,
date_time__range=(validated_data.get('date_time_before', None),
validated_data.get('date_time_after', None))
).annotate(next_value=Window(
expression=Lead('value')),
second_next_value=Window(
expression=Lead('value', 2)),
prev_value=Window(Lag('value')),
second_prev_value=Window(Lag('value', 2))
).order_by('date_time').exclude(exclude_next, exclude_prev
).annotate(x=F('date_time'),
y=F('value')).values('x', 'y')

**Comment by M1ha-Shvn** [comment]
This library extends QuerySet system provided by [infi.clickhouse-orm](https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/docs/querysets.md#filtering). I'm not sure if window functions are implemented there, but I guess you can try using some existing `F` function or create custom wrapper based on this class. [Here is a code of F class](https://github.com/Infinidat/infi.clickhouse_orm/blob/develop/src/infi/clickhouse_orm/funcs.py#L234).

**Comment by M1ha-Shvn** [comment]
Closed for no reply
